### ISSUE TITLE
python process started by pyml behaves differently than a bare one

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#10]
i set the environment variables as required; then start pymlutop. then:
```
#require "pyml";;
Py.initialize ();;
Py.Run.ipython ();;
from matplotlib import pyplot

ImportError: dlopen(/Users/nbecker/Apps/anaconda/lib/python2.7/site-packages/matplotlib/backends/_macosx.so, 2): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/nbecker/Apps/anaconda/lib/libjpeg.8.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

pymlutop is aliased to `PYTHONHOME=/Users/nbecker/Apps/anaconda/ DYLD_LIBRARY_PATH=/Users/nbecker/Apps/anaconda/lib pymlutop

is there still some incompatibility coming from the path setup? hmm.

**Comment by thierry-martinez** [comment]
Thanks for the report. It should be fixed now: if you compile ``pyml`` from master,``pymlutop`` should work without setting any additionnal variable. Setting ``DYLD_LIBRARY_PATH`` prevented ``matplotlib`` from being imported.

**Comment by nilsbecker** [comment]
hi, thanks. i installed from opam now, version 20170708. i can indeed start pymlutop without setting variables. however on startup i get the message 
```
Unbound value Py.Object.format_repr.
```
not sure how much of a problem that is - did not test further.

**Comment by nilsbecker** [comment]
ok, starting pymlutop without setting up paths i still get the warning above; then after initializing when i try to start `Py.Run.ipython ()` i get an opaque python exception and ipython does not start. it seems that the anaconda python installation which has ipython is not picked up. 

when i still keep the path environment set as in the first post, i can successfully run ipython. i can also `import matplotlib`. but when i try `from matplotlib import pyplot` i still get the same ImportError as above.
