### ISSUE TITLE
installation complains about ld.conf

### ISSUE THREAD

**Issue by nilsbecker** [thierry-martinez/pyml#8]
i pinned the git repository, unfortunately opam update fails now:

```
### stdout ###
# ocamlfind install pyml py.mli pyml_compat.cmi pyml_arch.cmi pytypes.cmi pywrappers.cmi py.cmi pycaml.cmi pyml_compat.cmx pyml_arch.cmx pytypes.cmx pywrappers.cmx py.cmx pycaml.cmx pyml.cma pyml.cmxa pyml.cmxs pyml.a libpyml_stubs.a dllpyml_stubs.so META
# install pymltop /Users/nbecker/.opam/4.04.0+flambda/bin/pymltop
# install pymlutop /Users/nbecker/.opam/4.04.0+flambda/bin/pymlutop
### stderr ###
# [...]
# Installed /Users/nbecker/.opam/4.04.0+flambda/lib/pyml/pytypes.cmi
# Installed /Users/nbecker/.opam/4.04.0+flambda/lib/pyml/pyml_arch.cmi
# Installed /Users/nbecker/.opam/4.04.0+flambda/lib/pyml/pyml_compat.cmi
# Installed /Users/nbecker/.opam/4.04.0+flambda/lib/pyml/py.mli
# Installed /Users/nbecker/.opam/4.04.0+flambda/lib/pyml/META
# Installed /Users/nbecker/.opam/4.04.0+flambda/lib/stublibs/dllpyml_stubs.so
# Installed /Users/nbecker/.opam/4.04.0+flambda/lib/stublibs/dllpyml_stubs.so.owner
# ocamlfind: [WARNING] You have installed DLLs but the directory /Users/nbecker/.opam/4.04.0+flambda/lib/stublibs is not mentioned in ld.conf
# install: pymlutop: No such file or directory
# make: *** [install] Error 71
```

**Comment by thierry-martinez** [comment]
Oops, typo in the Makefile, sorry. Should be fixed now.

**Comment by nilsbecker** [comment]
actually, i am now still getting another error: 
```
#=== ERROR while installing pyml.20170314 =====================================#
# opam-version 1.2.2
# os           darwin
# command      make install PREFIX=/Users/nbecker/.opam/4.04.0+flambda
# path         /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314
# compiler     4.04.0+flambda
# exit-code    2
# env-file     /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314/pyml-87510-d2d111.env
# stdout-file  /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314/pyml-87510-d2d111.out
# stderr-file  /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314/pyml-87510-d2d111.err
### stderr ###
# make: *** No rule to make target `pyutop.ml', needed by `pyutop.cmo'.  Stop.
```

i pinned pyml to the inria git repository -- is that correct?

**Comment by thierry-martinez** [comment]
Fixed. Thanks.On 14 Mar 2017 7:54 pm, nilsbecker <notifications@github.com> wrote:actually, i am now still getting another error:
#=== ERROR while installing pyml.20170314 =====================================#
# opam-version 1.2.2
# os           darwin
# command      make install PREFIX=/Users/nbecker/.opam/4.04.0+flambda
# path         /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314
# compiler     4.04.0+flambda
# exit-code    2
# env-file     /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314/pyml-87510-d2d111.env
# stdout-file  /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314/pyml-87510-d2d111.out
# stderr-file  /Users/nbecker/.opam/4.04.0+flambda/build/pyml.20170314/pyml-87510-d2d111.err
### stderr ###
# make: *** No rule to make target `pyutop.ml', needed by `pyutop.cmo'.  Stop.

i pinned pyml to the inria git repository -- is that correct?

**Comment by nilsbecker** [comment]
installed successfully!
